---
pg_version: 16
etcd_cluster_name: pg-lab
patroni_scope: pg-lab
patroni_namespace: /db/

# PostgreSQL users
pg_superuser: postgres
pg_admin_user: admin
pg_replicator_user: replicator

# pgBouncer
pgbouncer_port: 6432

# Patroni API
patroni_api_port: 8008

# HAProxy
haproxy_write_port: 5000
haproxy_read_port: 5001
haproxy_stats_port: 7000
haproxy_stats_user: admin

# MinIO
minio_bucket: pg-backups

# Grafana
grafana_admin_user: admin
