[postgres]
pg1     ansible_host=192.168.56.11
pg2     ansible_host=192.168.56.12

[haproxy]
haproxy ansible_host=192.168.56.10

[etcd:children]
postgres
haproxy

[all:vars]
ansible_user=vlad
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
